export type LabelPair = {
  ur: string;
  en: string;
};

export const labels: Record<string, LabelPair> = {
  collectorId: { ur: 'Collector ID', en: 'Collector ID' },
  motherAlive: { ur: '', en: "Mother's Living Status" },
  motherSeparationReason: { ur: 'والدہ اور بچے کی علیحدگی کی وجہ', en: 'Reason for Mother-Child Separation' },
  motherEmploymentStatus: { ur: 'والدہ کا روزگار', en: 'Mother Employment Status' },
  motherIsGuardian: { ur: 'والدہ سرپرست ہیں', en: 'Mother Is Guardian' },
  registrationNumber: { ur: 'رجسٹریشن نمبر', en: 'Registration Number' },
  collectorName: { ur: 'جمع کرنے والے کا نام', en: 'Collector Name' },
  collectorProject: { ur: 'پراجیکٹ', en: 'Project' },
  collectorCnic: { ur: 'جمع کرنے والے کا CNIC', en: 'Collector CNIC' },
  collectorAddress: { ur: 'جمع کرنے والے کا پتہ', en: 'Collector Address' },
  collectorContact: { ur: 'جمع کرنے والے کا رابطہ', en: 'Collector Contact' },
  fatherName: { ur: 'والد کا نام', en: 'Father Name' },
  fatherDob: { ur: 'والد کی تاریخ پیدائش', en: 'Father DOB' },
  fatherAge: { ur: 'والد کی عمر', en: 'Father Age' },
  fatherCnic: { ur: 'والد کا CNIC', en: 'Father CNIC' },
  fatherEducation: { ur: 'والد کی تعلیم', en: 'Father Education' },
  fatherTongue: { ur: 'والد کی مادری زبان', en: 'Father Mother Tongue' },
  fatherNativeArea: { ur: 'والد کا آبائی علاقہ', en: 'Father Native Area' },
  fatherOccupation: { ur: 'والد کا پیشہ', en: 'Father Occupation' },
  fatherDateOfDeath: { ur: 'وفات کی تاریخ', en: 'Father Date of Death' },
  fatherCauseOfDeath: { ur: 'وفات کا سبب', en: 'Father Cause of Death' },
  motherName: { ur: 'والدہ کا نام', en: 'Mother Name' },
  motherDob: { ur: 'والدہ کی تاریخ پیدائش', en: 'Mother DOB' },
  motherAge: { ur: 'والدہ کی عمر', en: 'Mother Age' },
  motherCnic: { ur: 'والدہ کا CNIC', en: 'Mother CNIC' },
  motherEducation: { ur: 'والدہ کی تعلیم', en: 'Mother Education' },
  motherTongue: { ur: 'والدہ کی مادری زبان', en: 'Mother Tongue' },
  motherNativeArea: { ur: 'والدہ کا آبائی علاقہ', en: 'Mother Native Area' },
  motherContact: { ur: 'والدہ کا رابطہ', en: 'Mother Contact' },
  motherIsHousewife: { ur: 'گھر والی ہیں', en: 'Mother is Housewife' },
  motherOccupation: { ur: 'والدہ کا پیشہ', en: 'Mother Occupation' },
  motherMonthlyIncome: { ur: 'ماہانہ آمدنی', en: 'Monthly Income' },
  motherRemarried: { ur: 'دوبارہ شادی', en: 'Mother Remarried' },
  motherDeathDate: { ur: 'والدہ کی وفات کی تاریخ', en: 'Mother Death Date' },
  motherDeathCause: { ur: 'والدہ کی وفات کا سبب', en: 'Mother Death Cause' },
  guardianName: { ur: 'سرپرست کا نام', en: 'Guardian Name' },
  guardianRelationship: { ur: 'سرپرست کا یتیم سے تعلق', en: 'Guardian Relationship with Orphan' },
  guardianGender: { ur: 'سرپرست کی جنس', en: 'Guardian Gender' },
  guardianCnic: { ur: 'سرپرست کا CNIC', en: 'Guardian CNIC' },
  guardianEducation: { ur: 'سرپرست کی تعلیم', en: 'Guardian Education' },
  guardianMotherTongue: { ur: 'سرپرست کی مادری زبان', en: 'Guardian Mother Tongue' },
  guardianNativeArea: { ur: 'سرپرست کا آبائی علاقہ', en: 'Guardian Native Area' },
  guardianContact: { ur: 'سرپرست کا رابطہ', en: 'Guardian Contact' },
  guardianZakatStatus: { ur: 'زکات کی حیثیت', en: 'Guardian Zakat Status' },
  guardianOccupation: { ur: 'سرپرست کا پیشہ', en: 'Guardian Occupation' },
  guardianFamilyHolder: { ur: 'فیملی ہولڈر؟', en: 'Family Holder?' },
  guardianFamilyHolderAmount: { ur: 'فیملی ہولڈر رقم', en: 'Family Holder Amount' },
  guardianFamilyMembersCount: { ur: 'خاندان کے افراد کی تعداد', en: 'No. of Family Members' },
  guardianMonthlyIncome: { ur: 'سرپرست کی ماہانہ آمدنی', en: 'Guardian Monthly Income' },
  paternalGrandfatherName: { ur: 'دادا کا نام', en: 'Paternal Grandfather Name' },
  paternalGrandfatherAge: { ur: 'دادا کی عمر', en: 'Paternal Grandfather Age' },
  paternalGrandfatherOccupation: { ur: 'دادا کا پیشہ', en: 'Paternal Grandfather Occupation' },
  paternalGrandfatherIncome: { ur: 'دادا کی آمدنی', en: 'Paternal Grandfather Income' },
  maternalGrandfatherName: { ur: 'نانا کا نام', en: 'Maternal Grandfather Name' },
  maternalGrandfatherAge: { ur: 'نانا کی عمر', en: 'Maternal Grandfather Age' },
  maternalGrandfatherOccupation: { ur: 'نانا کا پیشہ', en: 'Maternal Grandfather Occupation' },
  maternalGrandfatherIncome: { ur: 'نانا کی آمدنی', en: 'Maternal Grandfather Income' },
  relativeInformationDisclosed: { ur: 'قریبی رشتہ داروں کی معلومات فراہم کرنا چاہتے ہیں؟', en: "Close Relatives' Information Disclosed" },
  province: { ur: 'صوبہ', en: 'Province' },
  city: { ur: 'شہر / قصبہ', en: 'City/Town' },
  district: { ur: 'ضلع', en: 'District' },
  tehsil: { ur: 'تحصیل', en: 'Tehsil' },
  residentialArea: { ur: 'رہائشی علاقہ / محلہ / گلی', en: 'Residential Area / Mohalla / Street' },
  fullAddress: { ur: 'مکمل پتہ', en: 'Full Address' },
  longitude: { ur: 'طول بلد', en: 'Longitude' },
  latitude: { ur: 'عرض بلد', en: 'Latitude' },
  gpsAccuracyMeters: { ur: 'GPS درستگی میٹر میں', en: 'GPS Accuracy in meters' },
  gpsCapturedAt: { ur: 'GPS حاصل کرنے کا وقت', en: 'GPS Captured Time' },
  houseOwnershipStatus: { ur: 'گھر کی ملکیت', en: 'House Ownership Status' },
  monthlyRent: { ur: 'کتنا کرایہ؟', en: 'How much Rent?' },
  rentPaidBy: { ur: 'کرایہ کون ادا کرتا ہے؟', en: 'Who pays rent?' },
  houseOwner: { ur: 'گھر کا مالک', en: 'House Owner' },
  houseCondition: { ur: 'گھر کی حالت', en: 'House Condition' },
  residenceStructureType: { ur: 'رہائش کی ساخت کی قسم', en: 'Residence Structure Type' },
  residenceCategory: { ur: 'رہائش کی قسم', en: 'Residence Category' },
  houseConditionRemarks: { ur: 'گھر کی حالت کی تفصیل', en: 'House Condition Remarks' },
  electricityAvailable: { ur: 'بجلی کی سہولت میسر ہے', en: 'Electricity Available' },
  gasAvailable: { ur: 'گیس کی سہولت میسر ہے', en: 'Gas Available' },
  waterAvailable: { ur: 'پانی کی سہولت میسر ہے', en: 'Water Available' },
  furnishingCondition: { ur: 'فرنیچر کی حالت', en: 'Furnishing Condition' },
  furnishingConditionRemarks: { ur: 'فرنیچر کی حالت کی تفصیل', en: 'Furnishing Condition Remarks' },
  childName: { ur: 'بچے کا نام', en: 'Child Name' },
  gender: { ur: 'جنس', en: 'Gender' },
  caste: { ur: 'ذات', en: 'Caste' },
  sect: { ur: 'مذہبی فرقہ', en: 'Sect' },
  religion: { ur: 'مذہب', en: 'Religion' },
  specifyReligion: { ur: 'مذہب کی وضاحت کریں', en: 'Specify Religion' },
  syedStatus: { ur: 'سید حیثیت', en: 'Syed Status' },
  nationality: { ur: 'شہریت', en: 'Nationality' },
  specifyNationality: { ur: 'شہریت کی وضاحت کریں', en: 'Specify Nationality' },
  bFormNumber: { ur: 'بی فارم نمبر', en: 'B-Form Number' },
  dateOfBirth: { ur: 'تاریخ پیدائش', en: 'Date of Birth' },
  age: { ur: 'عمر', en: 'Age' },
  totalSiblings: { ur: 'کل بہن بھائیوں کی تعداد', en: 'Total Number of Siblings' },
  totalBrothers: { ur: 'کل بھائی', en: 'Total Brothers' },
  totalSisters: { ur: 'کل بہنیں', en: 'Total Sisters' },
  registeredBrothers: { ur: 'رجسٹرڈ بھائی', en: 'Registered Brothers' },
  registeredSisters: { ur: 'رجسٹرڈ بہنیں', en: 'Registered Sisters' },
  siblingsUnder12: { ur: '12 سال سے کم بہن بھائی', en: 'Siblings Under 12' },
  childLivesWithMother: { ur: 'بچہ ماں کے ساتھ رہتا ہے', en: 'Child lives with mother' },
  livingSituationNotes: { ur: 'رہائشی صورتحال', en: 'Living Situation Notes' },
  healthStatus: { ur: 'صحت کی صورتحال', en: 'Health Status' },
  disabilityDetails: { ur: 'معذوری کی تفصیل', en: 'Disability Details' },
  disabilityType: { ur: 'معذوری کی نوعیت', en: 'Type of Disability' },
  disabilityCause: { ur: 'معذوری کی وجہ', en: 'Cause of Disability' },
  disabilityCauseDetails: { ur: 'حادثے/بیماری کی تفصیل', en: 'Accident/Illness Details' },
  disabilitySince: { ur: 'کب سے؟', en: 'Since When?' },
  treatmentOngoing: { ur: 'کیا علاج جاری ہے؟', en: 'Is Treatment Ongoing?' },
  chronicDisease: { ur: 'بیماری / طبی مسئلہ', en: 'Disease / Medical Condition' },
  specifyDisease: { ur: 'بیماری کی وضاحت کریں', en: 'Specify Disease' },
  illnessSince: { ur: 'بچہ کب سے بیمار ہے؟', en: 'Since when is the Child ill?' },
  treatmentPlace: { ur: 'علاج کہاں سے جاری ہے؟', en: 'Treatment Facility / Hospital' },
  monthlyMedicalExpenses: { ur: 'ماہانہ طبی اخراجات', en: 'Monthly Medical Expenses' },
  currentlyStudying: { ur: 'کیا بچہ اسکول میں زیرِ تعلیم ہے؟', en: 'School Enrollment' },
  notStudyingReason: { ur: 'پڑھائی نہ کرنے کی وجہ', en: 'Not Studying Reason' },
  educationStartCondition: { ur: 'کیا پڑھ رہا ہے؟', en: 'Islamic Studies Level' },
  currentClass: { ur: 'موجودہ جماعت', en: 'Current Grade / Class' },
  schoolName: { ur: 'اسکول کا نام', en: 'School Name' },
  schoolAddress: { ur: 'اسکول کا پتہ', en: 'School Address' },
  schoolDistanceKm: { ur: 'گھر سے اسکول کا فاصلہ (کلومیٹر)', en: 'Distance from Home (km)' },
  schoolTransportMode: { ur: 'اسکول کیسے جاتا ہے؟', en: 'Mode of Transportation' },
  schoolStudyingSince: { ur: 'اسکول کب سے جا رہا ہے؟', en: 'Studying Since' },
  enrolledInMadrasa: { ur: 'کیا بچہ مدرسہ / مکتب میں زیرِ تعلیم ہے؟', en: 'Madrasa / Maktab Enrollment' },
  madrasaName: { ur: 'مدرسہ / مکتب کا نام', en: 'Madrasa / Maktab Name' },
  madrasaEducationDetails: { ur: 'پتہ', en: 'Address' },
  educationFeeStatus: { ur: 'تعلیمی فیس کی حیثیت', en: 'Education Fee Status' },
  educationFree: { ur: 'تعلیم مفت ہے؟', en: 'Is Education Free?' },
  monthlySchoolFee: { ur: 'ماہانہ فیس', en: 'Monthly Fee' },
  educationUndertakingAccepted: { ur: 'تعلیمی اقرار نامہ', en: 'Education Undertaking' },
  currentSkillLearning: { ur: 'کیا بچہ اس وقت کوئی ہنر سیکھ رہا ہے؟', en: 'Is the Child Currently Learning Any Skill?' },
  currentSkill: { ur: 'موجودہ سیکھا جانے والا ہنر', en: 'Current Skill' },
  childHobbies: { ur: 'بچے کا مشغلہ / دلچسپی', en: "Child's Hobby" },
  technicalSkillInterest: { ur: 'کیا بچہ کسی ٹیکنیکل ہنر میں دلچسپی رکھتا ہے؟', en: 'Interested in Learning Technical Skills?' },
  technicalSkill: { ur: 'مطلوبہ ٹیکنیکل ہنر', en: 'Technical Skill Interest' },
  careerGoal: { ur: 'مقصدِ زندگی', en: 'Career Goal' },
  technicalInterest: { ur: 'تکنیکی دلچسپی', en: 'Technical Interest' },
  learningSkill: { ur: 'سیکھنے کی صلاحیت', en: 'Learning Skill' },
  totalFamilyMembers: { ur: 'ایک ہی کچن پر رہنے والے خاندان کے کل افراد', en: 'Total Family Members (Living Together with One Kitchen)' },
  householdHasMonthlyIncome: { ur: 'کیا گھر کی کوئی ماہانہ آمدنی ہے؟', en: 'Does the Household Have Any Monthly Income?' },
  childMonthlyIncome: { ur: 'بچے کی ماہانہ آمدنی', en: 'Monthly Income of Child' },
  childEarnsIncome: { ur: 'کیا بچہ کوئی آمدنی حاصل کرتا ہے؟', en: 'Does the Child Earn Any Income?' },
  childWorkNature: { ur: 'بچے کا کام / ذریعہ آمدن', en: 'Nature of Work' },
  householdEarnersCount: { ur: 'گھر میں کمانے والے افراد کی تعداد', en: 'Number of Earning Members' },
  totalHouseholdIncome: { ur: 'مجموعی ماہانہ گھریلو آمدنی', en: 'Total Monthly Household Income' },
  receivingOtherAid: { ur: 'کیا خاندان کو کسی ذریعے سے امداد مل رہی ہے؟', en: 'Is the Family Receiving Financial Assistance from Any Source?' },
  otherAidSource: { ur: 'امداد فراہم کرنے والا ادارہ / فرد', en: 'Assistance Source' },
  monthlyAidAmount: { ur: 'ماہانہ امداد کی رقم', en: 'Monthly Assistance Amount' },
  assistanceApplied: { ur: 'کیا خاندان نے کہیں امداد کے لیے درخواست دی ہے؟', en: 'Has the Family Applied Anywhere for Assistance?' },
  assistanceAppliedWhere: { ur: 'کہاں اپلائی کیا ہے؟', en: 'Where the family has applied?' },
  notAppliedElsewhereReason: { ur: 'دوسری جگہ درخواست نہ دینے کی وجہ', en: 'Not Applied Elsewhere Reason' },
  guardianSignatureFileKey: { ur: 'سرپرست کے دستخط کی فائل کی', en: 'Guardian Signature File Key' },
  termsAccepted: { ur: 'شرائط قبول کی گئی ہیں', en: 'Terms Accepted' },
  termsAcceptedAt: { ur: 'شرائط قبول کرنے کی تاریخ', en: 'Terms Accepted At' },
};
