export type LabelPair = {
  ur: string;
  en: string;
};

export const labels: Record<string, LabelPair> = {
  collectorId: { ur: 'Collector ID', en: 'Collector ID' },
  registrationNumber: { ur: 'رجسٹریشن نمبر', en: 'Registration Number' },
  collectorName: { ur: 'جمع کرنے والے کا نام', en: 'Collector Name' },
  collectorProject: { ur: 'پراجیکٹ', en: 'Project' },
  collectorCnic: { ur: 'جمع کرنے والے کا CNIC', en: 'Collector CNIC' },
  collectorAddress: { ur: 'جمع کرنے والے کا پتہ', en: 'Collector Address' },
  collectorContact: { ur: 'جمع کرنے والے کا رابطہ', en: 'Collector Contact' },
  fatherName: { ur: 'والد کا نام', en: 'Father Name' },
  fatherDob: { ur: 'والد کی تاریخ پیدائش', en: 'Father DOB' },
  fatherAge: { ur: 'والد کی عمر', en: 'Father Age' },
  fatherCnic: { ur: 'والد کا CNIC', en: 'Father CNIC' },
  fatherEducation: { ur: 'والد کی تعلیم', en: 'Father Education' },
  fatherOccupation: { ur: 'والد کا پیشہ', en: 'Father Occupation' },
  fatherDateOfDeath: { ur: 'وفات کی تاریخ', en: 'Father Date of Death' },
  fatherCauseOfDeath: { ur: 'وفات کا سبب', en: 'Father Cause of Death' },
  motherName: { ur: 'والدہ کا نام', en: 'Mother Name' },
  motherDob: { ur: 'والدہ کی تاریخ پیدائش', en: 'Mother DOB' },
  motherAge: { ur: 'والدہ کی عمر', en: 'Mother Age' },
  motherCnic: { ur: 'والدہ کا CNIC', en: 'Mother CNIC' },
  motherEducation: { ur: 'والدہ کی تعلیم', en: 'Mother Education' },
  motherTongue: { ur: 'ابتدائی زبان', en: 'Mother Tongue' },
  motherNativeArea: { ur: 'مادر کا آبائی علاقہ', en: 'Mother Native Area' },
  motherContact: { ur: 'والدہ کا رابطہ', en: 'Mother Contact' },
  motherIsHousewife: { ur: 'گھر والی ہیں', en: 'Mother is Housewife' },
  motherOccupation: { ur: 'والدہ کا پیشہ', en: 'Mother Occupation' },
  motherMonthlyIncome: { ur: 'ماہانہ آمدنی', en: 'Monthly Income' },
  motherRemarried: { ur: 'دوبارہ شادی', en: 'Mother Remarried' },
  motherDeathDate: { ur: 'والدہ کی وفات کی تاریخ', en: 'Mother Death Date' },
  motherDeathCause: { ur: 'والدہ کی وفات کا سبب', en: 'Mother Death Cause' },
  guardianName: { ur: 'سرپرست کا نام', en: 'Guardian Name' },
  guardianRelationship: { ur: 'سرپرست کا رشتہ', en: 'Guardian Relationship' },
  guardianCnic: { ur: 'سرپرست کا CNIC', en: 'Guardian CNIC' },
  guardianEducation: { ur: 'سرپرست کی تعلیم', en: 'Guardian Education' },
  guardianMotherTongue: { ur: 'سرپرست کی مادری زبان', en: 'Guardian Mother Tongue' },
  guardianNativeArea: { ur: 'سرپرست کا آبائی علاقہ', en: 'Guardian Native Area' },
  guardianContact: { ur: 'سرپرست کا رابطہ', en: 'Guardian Contact' },
  guardianZakatStatus: { ur: 'زکات کی حیثیت', en: 'Guardian Zakat Status' },
  guardianOccupation: { ur: 'سرپرست کا پیشہ', en: 'Guardian Occupation' },
  guardianMonthlyIncome: { ur: 'سرپرست کی ماہانہ آمدنی', en: 'Guardian Monthly Income' },
  city: { ur: 'شہر', en: 'City' },
  district: { ur: 'ضلع', en: 'District' },
  tehsil: { ur: 'تحصیل', en: 'Tehsil' },
  residentialArea: { ur: 'رہائشی علاقہ', en: 'Residential Area' },
  fullAddress: { ur: 'مکمل پتہ', en: 'Full Address' },
  longitude: { ur: 'طول بلد', en: 'Longitude' },
  latitude: { ur: 'عرض بلد', en: 'Latitude' },
  houseOwnershipStatus: { ur: 'گھر کی ملکیت', en: 'House Ownership Status' },
  monthlyRent: { ur: 'ماہانہ کرایہ', en: 'Monthly Rent' },
  houseOwner: { ur: 'گھر کا مالک', en: 'House Owner' },
  houseCondition: { ur: 'گھر کی حالت', en: 'House Condition' },
  furnishingCondition: { ur: 'فرنیچر کی حالت', en: 'Furnishing Condition' },
  childName: { ur: 'بچے کا نام', en: 'Child Name' },
  gender: { ur: 'جنس', en: 'Gender' },
  caste: { ur: 'ذات', en: 'Caste' },
  sect: { ur: 'مذہبی فرقہ', en: 'Sect' },
  bFormNumber: { ur: 'بی فارم نمبر', en: 'B-Form Number' },
  dateOfBirth: { ur: 'تاریخ پیدائش', en: 'Date of Birth' },
  age: { ur: 'عمر', en: 'Age' },
  totalBrothers: { ur: 'کل بھائی', en: 'Total Brothers' },
  totalSisters: { ur: 'کل بہنیں', en: 'Total Sisters' },
  registeredBrothers: { ur: 'رجسٹرڈ بھائی', en: 'Registered Brothers' },
  registeredSisters: { ur: 'رجسٹرڈ بہنیں', en: 'Registered Sisters' },
  siblingsUnder12: { ur: '12 سال سے کم بہن بھائی', en: 'Siblings Under 12' },
  childLivesWithMother: { ur: 'بچہ ماں کے ساتھ رہتا ہے', en: 'Child lives with mother' },
  livingSituationNotes: { ur: 'رہائشی صورتحال', en: 'Living Situation Notes' },
  healthStatus: { ur: 'صحت کی حالت', en: 'Health Status' },
  disabilityDetails: { ur: 'معذوری کی تفصیل', en: 'Disability Details' },
  treatmentPlace: { ur: 'علاج کی جگہ', en: 'Treatment Place' },
  monthlyMedicalExpenses: { ur: 'ماہانہ طبی اخراجات', en: 'Monthly Medical Expenses' },
  currentlyStudying: { ur: 'فی الحال پڑھ رہا ہے', en: 'Currently Studying' },
  notStudyingReason: { ur: 'پڑھائی نہ کرنے کی وجہ', en: 'Not Studying Reason' },
  educationStartCondition: { ur: 'تعلیم شروع کرنے کی حالت', en: 'Education Start Condition' },
  currentClass: { ur: 'موجودہ جماعت', en: 'Current Class' },
  schoolName: { ur: 'اسکول کا نام', en: 'School Name' },
  schoolAddress: { ur: 'اسکول کا پتہ', en: 'School Address' },
  enrolledInMadrasa: { ur: 'مدرسے میں داخلہ', en: 'Enrolled in Madrasa' },
  madrasaName: { ur: 'مدرسے کا نام', en: 'Madrasa Name' },
  madrasaEducationDetails: { ur: 'مدرسے کی تعلیمی تفصیل', en: 'Madrasa Education Details' },
  educationFeeStatus: { ur: 'تعلیمی فیس کی حیثیت', en: 'Education Fee Status' },
  monthlySchoolFee: { ur: 'ماہانہ اسکول فیس', en: 'Monthly School Fee' },
  careerGoal: { ur: 'مقصدِ زندگی', en: 'Career Goal' },
  technicalInterest: { ur: 'تکنیکی دلچسپی', en: 'Technical Interest' },
  learningSkill: { ur: 'سیکھنے کی صلاحیت', en: 'Learning Skill' },
  childMonthlyIncome: { ur: 'بچے کی ماہانہ آمدنی', en: 'Child Monthly Income' },
  householdEarnersCount: { ur: 'گھرانے میں کمائی کرنے والوں کی تعداد', en: 'Household Earners Count' },
  totalHouseholdIncome: { ur: 'کل خاندانی آمدنی', en: 'Total Household Income' },
  receivingOtherAid: { ur: 'دوسری امداد حاصل کر رہا ہے', en: 'Receiving Other Aid' },
  otherAidSource: { ur: 'دوسری امداد کا ماخذ', en: 'Other Aid Source' },
  monthlyAidAmount: { ur: 'ماہانہ امداد کی رقم', en: 'Monthly Aid Amount' },
  notAppliedElsewhereReason: { ur: 'دوسری جگہ درخواست نہ دینے کی وجہ', en: 'Not Applied Elsewhere Reason' },
  principalName: { ur: 'پرنسپل کا نام', en: 'Principal Name' },
  institutionName: { ur: 'ادارے کا نام', en: 'Institution Name' },
  verifiedStudentName: { ur: 'درست شدہ طالب علم کا نام', en: 'Verified Student Name' },
  verifiedFatherName: { ur: 'درست شدہ والد کا نام', en: 'Verified Father Name' },
  verifiedClass: { ur: 'درست شدہ کلاس', en: 'Verified Class' },
  verifiedMonthlyFee: { ur: 'درست شدہ ماہانہ فیس', en: 'Verified Monthly Fee' },
  principalSignatureFileKey: { ur: 'پرنسپل کا دستخطی فائل کی', en: 'Principal Signature File Key' },
  institutionStampFileKey: { ur: 'ادارے کا اسٹیمپ فائل کی', en: 'Institution Stamp File Key' },
  imamName: { ur: 'امام کا نام', en: 'Imam Name' },
  mosqueName: { ur: 'مسجد کا نام', en: 'Mosque Name' },
  neighborhoodCity: { ur: 'محلے/شہر', en: 'Neighborhood/City' },
  imamMobile: { ur: 'امام کا موبائل', en: 'Imam Mobile' },
  motherZakatStatus: { ur: 'والدہ کی زکات کی حیثیت', en: 'Mother Zakat Status' },
  imamSignatureFileKey: { ur: 'امام کا دستخطی فائل کی', en: 'Imam Signature File Key' },
  mosqueStampFileKey: { ur: 'مسجد کا اسٹیمپ فائل کی', en: 'Mosque Stamp File Key' },
  guardianSignatureFileKey: { ur: 'سرپرست کے دستخط کی فائل کی', en: 'Guardian Signature File Key' },
  termsAccepted: { ur: 'شرائط قبول کی گئی ہیں', en: 'Terms Accepted' },
  termsAcceptedAt: { ur: 'شرائط قبول کرنے کی تاریخ', en: 'Terms Accepted At' },
};
